[package]
name = "gestion_hospitaliere"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = "0.4"
colored = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bcrypt = "0.16.0"